version: "3.8"
services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/12345678
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol for API connections

  app:
    build: .
    container_name: recommendation-system
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=12345678
      - NEO4J_DATABASE=neo4j
      - PORT=3000
    ports:
      - "3000:3000"
    command: ["sh", "/entrypoint.sh"]
